# Generated by Django 5.0.6 on 2024-06-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_orderdetails_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
